added flags and internaldate capabilites for MULTIAPPEND
mjs/imapclient pull request #462
Opened 2021-12-30 23:19 UTC by d70-t

While in #195 it was suggested to implement a `multiappend` function in a way supporting flags and internal date, this was not implemented in #399.

This PR adds the suggested functionality (iterator over `{'msg': ...[, 'flags': ...][, 'date': ...]}`-dicts) in a backwards-compatible manner.

2022-01-04 22:51 UTC, mjs commented
Thanks very much. I’m on holidays at the moment with limited connectivity but will take a proper look on my return.

On Fri, 31 Dec 2021, at 12:19, Tobias Kölling wrote:
> While in #195 <https://github.com/mjs/imapclient/issues/195> it was suggested to implement a `multiappend` function in a way supporting flags and internal date, this was not implemented in #399 <https://github.com/mjs/imapclient/pull/399>.
> 
> This PR adds the suggested functionality (iterator over `{'msg': ...[, 'flags': ...][, 'date': ...]}`-dicts) in a backwards-compatible manner.
> 
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/mjs/imapclient/pull/462
> 
> Commit Summary
> 
>  * bc6a9c3 <https://github.com/mjs/imapclient/pull/462/commits/bc6a9c3f4e12531ebb4b21ff5b0909a2ac93890a> added flags and internaldate capabilites for MULTIAPPEND
> File Changes
> 
> (2 files <https://github.com/mjs/imapclient/pull/462/files>)
> 
>  * *M* imapclient/imapclient.py <https://github.com/mjs/imapclient/pull/462/files#diff-4ac79f7593b1992a3ed27d2af46d918be51687192ebdda54059cd74e4d590a3b> (13)
>  * *M* tests/test_imapclient.py <https://github.com/mjs/imapclient/pull/462/files#diff-ffc113f72c530719afe9d3fe0dcccc11aed1a766b2bbe524f9c300631b94b441> (42)
> Patch Links:
> 
>  * https://github.com/mjs/imapclient/pull/462.patch
>  * https://github.com/mjs/imapclient/pull/462.diff
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/mjs/imapclient/pull/462>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAADVEI3HAGHQQBBDAPMOJTUTTSIRANCNFSM5LAOOV3A>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
>

2022-01-25 10:18 UTC, mjs requested changes
This looks great. Thanks for adding tests as well.

 Would you mind updating the docstring to mention the approach of passing a dict with the internaldate and flags? Once that's in place this is good to merge.

2022-01-25 10:56 UTC, d70-t commented
Thanks for reviewing @mjs. I've made the requested changes to the docstring.

2022-01-25 11:01 UTC, mjs approved these changes
Perfect, thanks!

2022-01-25 11:02 UTC, merged